### ISSUE TITLE
wrong TV for impl

### ISSUE THREAD

**Issue by PtrMan** [opennars/ALANN2018#25]
<cat --> [bites]>.
<dog --> [bites]>.
<<cat --> $1> ==> <dog --> $1>>?
mr_allan
?Answer:[ 1ms]<<cat --> $1> ==> <dog --> $1>>{1.00 0.45}
mr_nars4
Answer: <<cat --> $1> ==> <dog --> $1>>. %1.00;0.40%

**Comment by TonyLo1** [comment]
I can see that it's different. Why is it wrong?

**Comment by patham9** [comment]
Not wrong ALANN is right, it's an issue I introduced. (not in ALANN)

**Comment by patham9** [comment]
Since OpenNARS can introduce multiple variables at once, I decided to penalize each introduced variable so that too general hypothesis will gain evidence more slowly than the specific ones, similar as what would happen if each variable is introduced extra by the var intro rule. Maybe this won't be required though.

**Comment by PtrMan** [comment]
Oh right, I recall the code in OpenNARS which is doing this. Will close this now.
